import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.NormNum
#check Real.cos_bound
#check Real.sin_bound
#check Real.one_sub_sq_div_two_le_cos
#check Complex.exp_ofReal_mul_I
#check Complex.norm_cos_add_sin_mul_I
#check Complex.hasDerivAt_exp
#check Complex.hasDerivAt_exp_mul_I
#check Complex.exp_mul_I_periodic
#check Complex.exp_add_two_pi_mul_I
#check Matrix.toEuclideanCLM_apply
#check Matrix.mulVec_diagonal
#check Complex.exp_pi_mul_I
